swagger: '2.0'
info:
  version: 1.0.0
  title: LoopBack Application
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - application/xml
  - text/xml
produces:
  - application/json
  - application/xml
  - text/xml
  - application/javascript
  - text/javascript
paths:
  '/Recipes':
    post:
      tags:
        - Recipe
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Recipe_create
      parameters:
        - name: accessToken
          in: query
          description: User access token
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Recipe'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Recipe'
      deprecated: false
    get:
      tags:
        - Recipe
      summary: Get all recipes
      operationId: Recipe_get
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/RecipeList'
      deprecated: false
  '/Recipes/filter/{query}':
    get:
      tags:
        - Recipe
      summary: Searches a recipes by substring
      operationId: Recipe_filtered_get
      parameters:
        - name: query
          in: path
          description: Substring to search for
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/RecipeList'
      deprecated: false

  '/Recipes/{id}':
    head:
      tags:
        - Recipe
      summary: Check whether a model instance exists in the data source.
      operationId: Recipe_exists__head_Recipes_id
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: integer
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    get:
      tags:
        - Recipe
      summary: Find a model instance by id from the data source.
      operationId: Recipe_findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: integer
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Recipe'
      deprecated: false
    delete:
      tags:
        - Recipe
      summary: Delete a model instance by id from the data source.
      operationId: Recipe_deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: number
          format: JSON
        - name: accessToken
          in: query
          description: User access token
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - Recipe
      summary: Update attributes for a model instance and persist it into the data source.
      operationId: Recipe_prototype_updateAttributes
      parameters:
        - name: accessToken
          in: query
          description: User access token
          required: true
          type: string
          format: JSON
        - name: id
          in: path
          description: PersistedModel id
          required: true
          type: integer
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Recipe'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Recipe'
      deprecated: false
  /Recipes/count:
    get:
      tags:
        - Recipe
      summary: Count instances of the model.
      operationId: Recipe_count
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
definitions:
  Credential:
    properties:
      username:
        type: string
      password:
        type: string
  Recipe:
    properties:
      ingredients:
        type: array
        items:
          type: string
      name:
        type: string
      description:
        type: string
      id:
        type: integer
        format: int64
    required:
      - name
      - id
    additionalProperties: false
  RecipeList:
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Recipe'
tags:
  - name: Recipe
